# Generated by Django 4.1 on 2022-08-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emp_salary_emp_table_delete_album_delete_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_salary',
            name='id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emp_table'),
        ),
    ]
